    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimento', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimento', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimentoTM', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimentoTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('PianoRifornimento', 'YPianoRifornimento', '1', 'Y', 'N');
