    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.ordese.AttivitaEsecutiva', 'it.testori.thip.produzione.ordese.YAttivitaEsecutiva', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.ordese.AttivitaEsecutivaTM', 'it.testori.thip.produzione.ordese.YAttivitaEsecutivaTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('AttivitaEsecutiva', 'YAttivitaEsecutiva', '1', 'Y', 'N');
