    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.magazzino.generalemag.Lotto', 'it.testori.thip.magazzino.generalemag.YLotto', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.magazzino.generalemag.LottoTM', 'it.testori.thip.magazzino.generalemag.YLottoTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('Lotto', 'YLotto', '1', 'Y', 'N');
