    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenRigaPrm', 'it.testori.thip.vendite.documentoVE.YDocumentoVenRigaPrm', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenRigaPrmTM', 'it.testori.thip.vendite.documentoVE.YDocumentoVenRigaPrmTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('DocumentoVenditaRigaPrm', 'YDocumentoVenRigaPrm', '1', 'Y', 'N');
