# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.ArticoloDatiProduz', 'it.testori.thip.base.articolo.YArticoloDatiProduz', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.base.articolo.ArticoloDatiProduzTM', 'it.testori.thip.base.articolo.YArticoloDatiProduzTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('ArticoloDatiProduz', 'YArticoloDatiProduz', '1', 'N');
