# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.GenerazionePianoRiforn', 'it.testori.thip.produzione.rifornLinea.YGenerazionePianoRiforn', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.vendite.documentoVE.DocumentoVenRigaPrmTM', 'it.testori.thip.vendite.documentoVE.YDocumentoVenRigaPrmTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('DocumentoVenditaRigaPrm', 'YDocumentoVenRigaPrm', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimento', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimento', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimentoTM', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimentoTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('PianoRifornimento', 'YPianoRifornimento', '1', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimentoRiga', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimentoRiga', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.rifornLinea.PianoRifornimentoRigaTM', 'it.testori.thip.produzione.rifornLinea.YPianoRifornimentoRigaTM', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('PianoRifornimentoRiga', 'YPianoRifornimentoRiga', '1', 'N');
