# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED,REPLACEMENT_APP) VALUES ('it.thera.thip.magazzino.generalemag.Lotto', 'it.testori.thip.magazzino.generalemag.YLotto', '0', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED,REPLACEMENT_APP) VALUES ('it.thera.thip.magazzino.generalemag.LottoTM', 'it.testori.thip.magazzino.generalemag.YLottoTM', '0', 'N', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED,REPLACEMENT_APP) VALUES ('Lotto', 'YLotto', '1', 'N', 'N');