    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.AttivitaProduttiva', 'it.testori.thip.datiTecnici.modpro.YAttivitaProduttiva', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.datiTecnici.modpro.AttivitaProduttivaTM', 'it.testori.thip.datiTecnici.modpro.YAttivitaProduttivaTM', '0', 'Y', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('AttivitaProduttiva', 'YAttivitaProduttiva', '1', 'Y', 'N');
